name: Deploy Astro to GitHub Pages

on:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main
  # Allows you to manually trigger the workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # You can specify your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist